name: DL_Track_US
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip=22.2.2
  - pip:
    - customtkinter==5.2.2
    - jupyter==1.0.0
    - Keras==2.10.0
    - matplotlib==3.6.1
    - numpy==1.23.4
    - opencv-contrib-python==4.6.0.66
    - openpyxl==3.0.10
    - orientationpy==0.2.0.4
    - pandas==1.5.1
    - Pillow==9.2.0
    - pre-commit==2.17.0
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - sewar==0.4.5
    - shapely==2.0.5
    - tensorflow==2.10.0
    - tqdm==4.64.1
